# Generated by Django 5.2.17 on 2026-09-27 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi'), ('Bandung', 'Bandung'), ('Semarang', 'Semarang'), ('Yogyakarta', 'Yogyakarta'), ('Surabaya', 'Surabaya'), ('Malang', 'Malang'), ('Medan', 'Medan'), ('Makassar', 'Makassar')], default='Depok', max_length=50)),
                ('task_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('repotting', 'Repotting'), ('harvesting', 'Harvesting'), ('inspection', 'Inspection')], max_length=20)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['due_date', 'is_completed', 'created_at'],
            },
        ),
    ]
