# Generated by Django 5.2.17 on 2026-09-30 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('seed', 'Seed'), ('seedling', 'Seedling'), ('cutting', 'Cutting'), ('plant', 'Plant')], max_length=20)),
                ('plant_name', models.CharField(blank=True, default='', help_text='Nama tanaman (untuk filter Tanaman)', max_length=100)),
                ('city', models.CharField(choices=[('Jakarta', 'Jakarta'), ('Bogor', 'Bogor'), ('Depok', 'Depok'), ('Tangerang', 'Tangerang'), ('Bekasi', 'Bekasi'), ('Bandung', 'Bandung'), ('Semarang', 'Semarang'), ('Yogyakarta', 'Yogyakarta'), ('Surabaya', 'Surabaya'), ('Malang', 'Malang'), ('Medan', 'Medan'), ('Makassar', 'Makassar')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('giveaway', 'Give Away'), ('swap', 'Swap')], max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('completed', 'Completed')], default='available', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
