# Generated by Django 5.2.17 on 2026-10-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seed_exchange', '0002_seedexchange_reserved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedexchange',
            name='contact',
            field=models.CharField(default='', help_text='Wajib: cara menghubungimu (No. WA / email / sosmed)', max_length=120),
        ),
        migrations.AlterField(
            model_name='seedexchange',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('requested', 'Menunggu konfirmasi'), ('reserved', 'Reserved'), ('completed', 'Completed')], default='available', max_length=20),
        ),
    ]
