# Generated by Django 5.2.17 on 2026-09-30 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecopatch_name', models.CharField(blank=True, help_text='Nama EcoPatch (sementara, akan diganti FK ke EcoPatch)', max_length=200)),
                ('plant_name', models.CharField(blank=True, help_text='Nama tanaman (sementara, akan diganti FK ke Plant)', max_length=200)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('plant_condition', models.CharField(choices=[('healthy', 'Healthy'), ('needs_attention', 'Needs Attention'), ('wilting', 'Wilting'), ('flowering', 'Flowering'), ('fruiting', 'Fruiting'), ('ready_to_harvest', 'Ready to Harvest')], default='healthy', max_length=20)),
                ('plant_height', models.FloatField(blank=True, help_text='Tinggi tanaman (cm), opsional', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
