# Generated by Django 5.2.17 on 2026-10-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gardenjournal',
            name='cover_pattern',
            field=models.CharField(choices=[('brushes', 'Brushes'), ('dots', 'Dots'), ('flowers', 'Flowers'), ('seeds', 'Seeds'), ('soft', 'Soft')], default='flowers', help_text='Sampul buku jurnal', max_length=20),
        ),
    ]
