# Generated by Django 5.2.17 on 2026-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden_journal', '0002_gardenjournal_cover_pattern'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gardenjournal',
            name='cover_pattern',
            field=models.CharField(choices=[('brushes', 'Brushes'), ('dots', 'Dots'), ('flowers', 'Flowers'), ('seeds', 'Seeds'), ('soft', 'Soft'), ('leaves', 'Leaves')], default='flowers', help_text='Sampul buku jurnal', max_length=20),
        ),
    ]
