# Generated by Django 5.2.17 on 2026-09-28 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoPatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('space_type', models.CharField(choices=[('balcony', 'Balcony'), ('indoor', 'Indoor'), ('terrace', 'Terrace'), ('rooftop', 'Rooftop'), ('small_yard', 'Small Yard')], max_length=20)),
                ('size_m2', models.PositiveIntegerField(blank=True, help_text='Ukuran ruang (m²)', null=True)),
                ('sunlight', models.CharField(blank=True, choices=[('full', 'Full Sun'), ('partial', 'Partial Sun'), ('shade', 'Shade')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('goal', models.TextField(blank=True, help_text='Tujuan berkebun')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eco_patches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatchPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('growing', 'Growing'), ('harvested', 'Harvested'), ('removed', 'Removed')], default='planned', max_length=20)),
                ('planted_at', models.DateField(blank=True, null=True)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='my_ecopatch.ecopatch')),
            ],
        ),
    ]
